// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIYK05et6vZuDni4i8DJS7dalItWCQ19o',
    appId: '1:203108233475:web:8f0b7f6aaf0e13bb6df936',
    messagingSenderId: '203108233475',
    projectId: 'webtoon-flutter-pab2',
    authDomain: 'webtoon-flutter-pab2.firebaseapp.com',
    storageBucket: 'webtoon-flutter-pab2.firebasestorage.app',
    measurementId: 'G-R9TP87V6D2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsi38bXZZQnmONnhwInamppkxjWWNvt3k',
    appId: '1:203108233475:android:39baaf3fd6cb11d16df936',
    messagingSenderId: '203108233475',
    projectId: 'webtoon-flutter-pab2',
    storageBucket: 'webtoon-flutter-pab2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfSYAtjQOKuN7tcEk1mp6UtOb7rUol2vw',
    appId: '1:203108233475:ios:1c6d7ebed198bbec6df936',
    messagingSenderId: '203108233475',
    projectId: 'webtoon-flutter-pab2',
    storageBucket: 'webtoon-flutter-pab2.firebasestorage.app',
    iosBundleId: 'com.example.webtoonFlutterPab2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfSYAtjQOKuN7tcEk1mp6UtOb7rUol2vw',
    appId: '1:203108233475:ios:1c6d7ebed198bbec6df936',
    messagingSenderId: '203108233475',
    projectId: 'webtoon-flutter-pab2',
    storageBucket: 'webtoon-flutter-pab2.firebasestorage.app',
    iosBundleId: 'com.example.webtoonFlutterPab2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIYK05et6vZuDni4i8DJS7dalItWCQ19o',
    appId: '1:203108233475:web:63b57d0277dde9f26df936',
    messagingSenderId: '203108233475',
    projectId: 'webtoon-flutter-pab2',
    authDomain: 'webtoon-flutter-pab2.firebaseapp.com',
    storageBucket: 'webtoon-flutter-pab2.firebasestorage.app',
    measurementId: 'G-N46XPB7TGG',
  );
}
